### ISSUE TITLE
Find would traverse a leaf at path

### ISSUE THREAD

**Issue by benbrittain** [facebook/buck2#176]
I'm trying to migrate some Bazel logic that was implement as a `repository_rule`, when I got this error:

```
BUILD FAILED
Find would traverse a leaf at path: `buck-out/v2/gen/root/524f8da68ea2a374/third_party/__protobuf__/lib
```

This error is not particularly clear to me and I'm not sure how to proceed from it's output

**Comment by benbrittain** [comment]
This seems to have been related to not specifying a declared output as a directory.

**Comment by krallin** [comment]
Could you share a repro of where you hit this? Agreed that it's not clear what the error means but I'm afraid it's also not clear how you ran into it! :) 

My two guesses for this would have been

- Declaring [a projection that accesses a path inside a file](https://github.com/facebook/buck2/blob/main/app/buck2_build_api/src/artifact_groups/calculation.rs#L315-L323
- Declaring an output that is a path within a file

But I tried both of those and neither produces the output you saw. 

>  This seems to have been related to not specifying a declared output as a directory. 

That _seems_ rather surprising since declaring outputs as directories or files is actually just for validation.

**Comment by benbrittain** [comment]
I've failed to reproduce the exact scenario where I got this before, but I've encountered it again. In this case I have been trying to use `project`.  In fact, I'm generally not sure of when to use `project` 


```
    # Setup an artifact dir                                                         
    main_artifact_dir = ctx.attrs.environment[DefaultInfo].default_outputs[0]                                                                       
    artifact_dir = ctx.actions.declare_output("__artifacts")                                                                                            
    ctx.actions.symlink_file(artifact_dir, main_artifact_dir)                                                                                          
                                                                                                                                                 
    srcs = {}                                                                                                                                    
    srcs["lib/addr2line.a"] = artifact_dir.project("lib/addr2line.a")                                                                 
    art = ctx.actions.symlinked_dir("__srcs", srcs)           
```

**Comment by krallin** [comment]
> In fact, I'm generally not sure of when to use project

Projected artifacts are for them you want to define an artifact that is a path within some other existing artifact (where the latter is a directory). It's primarily useful when you'd like to expose artifacts that have paths that overlap, which isn't normally allowed (so you declare the outermost artifact and then you use projections to generate others).

> The answer might be "you aren't allowed to symlink into other directories like this", which I think would be fair?

It's not super clear to me what you're trying to do, so it's hard to answer with certainty.

That said, `symlink_file` does create *a symlink*, so you can't use a projection with that (because that's for directories), if you want to access only `addr2line.a` and you need it as an artifact  (not just a path on a command line, for which you could do `cmd_args(artifact_dir, format="{}/lib/addr2line.a")`), then your `environment` really needs to expose that as an individual artifact to you.

**Comment by krallin** [comment]
W.r.t. the original issue of the error message being not great, I found that bug and I'll put up a fix for it.

**Comment by benbrittain** [comment]
Thanks @krallin, I appreciate your help here.
