### ISSUE TITLE
target determinator?

### ISSUE THREAD

**Issue by ahornby** [facebook/buck2#247]
Hi,  what's the recommended way to do target determinator with buck2?  Secondary question, is there a buck2 slack or discord to ask questions like this? Thanks, Alex

**Comment by steveklabnik** [comment]
>  is there a buck2 slack or discord to ask questions like this? 

I am running one. It is not sanctioned by meta, as I do not work there: https://discord.gg/SmZasYt9

That said, the team has previously expressed that they're okay with asking questions like this on the tracker.

> what's the recommended way to do target determinator with buck2?

I do not know personally, as I'm still learning myself 😅

**Comment by stepancheg** [comment]
> what's the recommended way to do target determinator with buck2

There's no single recommended way to do target determination in buck2.

In simple cases in can be done like this:

```
vcs co previous revision
buck2 targets --show-unconfigured-target-hash //... > prev.txt
vcs co current revision
buck2 targets --show-unconfigured-target-hash //... > current.txt
```

then compare `prev.txt` and `current.txt`, which targets have different hashes, needs to be rebuilt.

This approach hashes all the files (belonging to targets) in the repository. If this is too expensive, more complex approach might be needed. For example, avoid hashing files (`--target-hash-file-mode=paths-only`) and additionally use `rdeps` query to find affected targets.

**Comment by ahornby** [comment]
As mentioned on the discord chat,  I've been thinking about target determinator (TD) scripts/drivers like the bazel one https://github.com/bazel-contrib/target-determinator.   Its in go,  maybe  we'll end up with a rust one like that for buck2 at some point, but that set me wondering: why is TD only for CI and not part of more regular build tooling
 
A good TD is nice because it works out only the targets needed, reducing irrelevant CI signal (e.g. perpetually broken targets) and making build actions hopefully more O(change) even if caches not populated.

Wouldn’t TD-like features be desirable outside CI as well?      So long as VCS can efficiently give list of files changed since known good base (e.g. main), seems like it might be.  Maybe in past it was too slow to construct and query graph twice while user waited (the bazel TD is pretty slow), but with buck2 maybe its not

**Comment by LegNeato** [comment]
Well, "known good base" gets complicated. Is it the last passing revision of the specific targets you touched? Or the last revision where all targets are passing? I've seen both ways. What happens if you change a file that touches a target that was previously failing...how do you know if the failure is caused by your changes or was preexisting? Where does the source control or build tool get this info?

In an ideal world local caching, shared caches, and remote execution remove the need for a TD. You build everything and the build system efficiently (and correctly) skips unnecessary work and reuses work already done. A TD is useful when the build system work to determine what work to do is _itself_ too much work or if your targets are too coarse to efficiently reuse work. So you encode some rough domain-specific rules and logic into a layer "above" the build system. TD is largely an optimization for CI IMHO...you are trading off correctness and purity for speed (and hopefully backfilling the correctness).

**Comment by ahornby** [comment]
@LegNeato I think a TD can be correct if the build is hermetic and thus honors the declared graph,  its basically just some graph queries after all.  In the cases like you raised, one runs the target (its better to be correct than fast!).   Non-hermetic buck1 builds made TD correctness hard inside meta, similar to why automated sparse profile creation didn't really work, as the graph they were based on wasn't complete

For what is "known good",  the user would be able to specify the good known base revision.  If they don't then the branch point from main/master would seem a reasonable default. 

TD like functionality has utility beyond speed, sub-setting the build is super useful for signal as well, which would be great to have locally

**Comment by ahornby** [comment]
closing, buck2 TD is in https://github.com/facebookincubator/buck2-change-detector
