### ISSUE TITLE
`buck2 build` does not inherit all the environment from the calling shell

### ISSUE THREAD

**Issue by cbarrete** [facebook/buck2#306]
(Feel free to edit the title if it is not accurate)

Hi, I'm trying to use Buck2 in tandem with Nix to get a reproducible toolchain. My issue is that Buck2 doesn't pick up a temporarily installed toolchain, i.e. a toolchain only available in the current shell.

To demonstrate:
```
> git clone -q https://github.com/facebook/buck2.git
> cd buck2/examples/hello_world
> buck2 init --git
> buck2 build :main
Action failed: root//:main (cxx_compile main.cpp)
Local command returned non-zero exit code <no exit code>
Reproduce locally: `clang++ -o buck-out/v2/gen/root/524f8da68ea2a374/__main__/__objects__/main.cpp.o @buck-out/v2/gen/root/524f8da68ea2a374/__main__/.cpp.argsfile -c ./main.cpp`
stdout:
stderr:
Spawning executable `clang++` failed: No such file or directory (os error 2)
Build ID: d5ac8b7f-14f7-4c25-8f9d-65a3c19f54ac
Jobs completed: 8. Time elapsed: 0.1s. Cache hits: 0%.
BUILD FAILED
Failed to build 'root//:main (prelude//platforms:default#524f8da68ea2a374)'
```

Which is fair enough:
```
> clang++
clang++: command not found
```

Let's remedy that:
```
> nix shell nixpkgs#clang
> clang --version
clang version 11.1.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /nix/store/2mzlcaibivy9aad0fswspl0g9fjpkg6m-clang-11.1.0/bin
```

What this does is bring clang into scope by spawning a new shell that has its PATH amended with the location of clang. clang is unavailable anywhere outside of this shell.

So let's try again:
```
> buck2 build :main
Action failed: root//:print (cxx_compile library.cpp)
Local command returned non-zero exit code <no exit code>
Reproduce locally: `clang++ -o buck-out/v2/gen/root/524f8da68ea2a374/__print__/__objects__/library.cpp.o @buck-out/v2/gen/root/524f8da68ea2a374/__print__/.cpp.argsfile -c ./library.cpp`
stdout:
stderr:
Spawning executable `clang++` failed: No such file or directory (os error 2)
Action failed: root//:main (cxx_compile main.cpp)
Local command returned non-zero exit code <no exit code>
Reproduce locally: `clang++ -o buck-out/v2/gen/root/524f8da68ea2a374/__main__/__objects__/main.cpp.o @buck-out/v2/gen/root/524f8da68ea2a374/__main__/.cpp.argsfile -c ./main.cpp`
stdout:
stderr:
Spawning executable `clang++` failed: No such file or directory (os error 2)
Build ID: d14c7295-79d7-40af-a332-697ffda7e8a8
Jobs completed: 5. Time elapsed: 0.0s. Cache hits: 0
BUILD FAILED
Failed to build 'root//:main (prelude//platforms:default#524f8da68ea2a374)'
```

Weird, let's try to reproduce that as suggested in the output:
```
> clang++ -o buck-out/v2/gen/root/524f8da68ea2a374/__main__/__objects__/main.cpp.o @buck-out/v2/gen/root/524f8da68ea2a374/__main__/.cpp.argsfile -c ./main.cpp
> file buck-out/v2/gen/root/524f8da68ea2a374/__main__/__objects__/main.cpp.o
buck-out/v2/gen/root/524f8da68ea2a374/__main__/__objects__/main.cpp.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

So my environment is fine, it just doesn't get picked up by Buck2.

I suspect that builds are somewhat isolated, but it is weird to me that some bits of the environment are picked up and others are not.

Is there a good way to solve this, besides just installing the toolchain globally (which works, but goes against my goal of not depending on global state, controlling the toolchain and providing a self-contained dev environment with my project)?

I suspect that this can be somehow solved by not using `system_cxx_toolchain` and writing something custom, but I don't know how to get started with this, and it seems that the current state isn't too far off from supporting this use case (which isn't Nix-specific, I assume that it would apply to any dev env tool).

Thanks

**Comment by thoughtpolice** [comment]
`buck2` starts a daemon in the background when you build a project, and the daemon keeps track of file state, the build cache directory, etc. Try `ps aux | grep 'buck2d\[hello_world\]'` (or just use `grep buck2d`) and you can see all the daemon instances you're running. Naturally, the daemon isn't going to inherit the modified `$PATH` that you get from `nix shell` (which is just another bash subshell, anyway.)

You need to `buck2 kill` the daemon (you can do so from the `hello_world` directory) and then try again; this will make your example get further, though note `system_cxx_toolchain` will assume LLD is present, so you'll probably have to fiddle with your `nix shell` invocation a bit more.

Really, for Nix users who want to use the upstream `buck2-prelude`, there should be a way to bootstrap the prelude's cxx_toolchain (at minimum) with nix, e.g. you'd have a `nix_cxx_toolchain` function to call instead of `system_cxx_toolchain`, and that function could do something like invoke `nix copy` to download a pre-built toolchain from https://cache.nixos.org; then you'd never even need to change your shell at all. I haven't tried this but it shouldn't be too hard if you're willing to give it a whirl.

**Comment by cbarrete** [comment]
Thanks for the detailed answer, it's obvious in hindsight but I didn't realize that there was a daemon running...

Regarding what you've said about `nix_cxx_toolchain`, that's roughly what I have in mind (not that I've given it a lot of thought), but I'll wait until I'm more invested in `buck2` before diving in, I'm still investigating for now :)
