### ISSUE TITLE
How to implement an object library?

### ISSUE THREAD

**Issue by zjturner** [facebook/buck2#334]
I’d like a rule that is basically cxx_library with link_style=“static”, but which doesn’t call the archiver and the output is every object, not a single archive.  All objects should be passed on the command line to subsequent dependencies.

Alternatively, what might work (I think it’s semantically identical) would be the link_whole attribute, but I’m wondering if there’s any gotchas?  Is it truly semantically identical?  Object libs often have better performance since the archive never has to be written to disk

**Comment by ndmitchell** [comment]
I think we use link whole a lot internally, but not sure how it gets wired in (on a mobile at the moment). What's the reason for wanting this?

**Comment by zjturner** [comment]
We have a very complicated CMake build that makes use of [object libraries](https://cmake.org/cmake/help/latest/command/add_library.html#object-libraries).  This would give us a direct 1:1 migration path.  We could probably use `link_whole` (although I'm still curious if there's any semantic difference between `link_whole` and passing in object files.  I don't think _there_ is), and I guess this would be a fine solution.  But I just wonder about the performance aspect of it.  It's not _bad_, I just wonder if an object library could be _better_.  

For example, say you've got 10 objects, each are 100MB.  you put them into an archive and `link_whole` them.  A single object changes, you have to write out a 1GB archive to the cache.  Conversely, if there's a cache hit on the 1GB archive you have to download that entire 1GB archive.  If they're just objects, you might already have 9/10 of them locally, and you only need to download 1/10 of them from the cache.  

So semantic differences / similarities aside, it seems like there's some could be some i/o and bandwidth benefits to linking as objects rather than as a whole archive.

But lmk if my thinking is wrong.

**Comment by cjhopman** [comment]
If the toolchain supports thin archives (looks like its `cxx_toolchain.linker_info.archive_contents == "thin"`), those performance concerns should be resolved (a thin archive basically is just a small index that references the objects outside of it).

That's not always available. Another thing to try would be to force using objects instead of archives. This can be set on the toolchain (`cxx_toolchain.linker_info.requires_objects = True` would do it i think) but that would affect all static libs. It looks like cxx_library also has a use_archives attr that can be set to False to disable archives for that lib.

The thin archives thing should be widely used, either of the approaches to forcing to use objects instead of archive might be less widely used and you may run into issues there.

**Comment by zjturner** [comment]
Thanks.  One of those should definitely suffice!
