### ISSUE TITLE
Hello world is broken on Mac

### ISSUE THREAD

**Issue by miaoyipu** [facebook/buck2#384]
Hi, team, it seems hello world is broken on my Mac (M1) due to prelude issue. 
I got

```
(base) ➜  hello_world git:(master) ✗ buck2 targets //...
Error parsing root//
From `load` at implicit location

Caused by:
    0: From `load` at prelude/prelude.bzl:8:6-29
    1: From `load` at prelude/native.bzl:15:6-52
    2: From `load` at prelude/apple/apple_bundle_macro_layer.bzl:8:6-32
    3: Error evaluating module: `prelude//apple/apple_bundle_config.bzl`
    4: error: Variable `typing` not found
         --> prelude/apple/apple_bundle_config.bzl:14:40
          |
       14 | def apple_bundle_config() -> dict[str, typing.Any]:
          |                                        ^^^^^^
          |
```

[This](https://github.com/facebook/buck2-prelude/commit/d7c786567439cc0c1a183f2bd12e70c3157e268c) is the first bad version, but it is broken for another error message
```
Caused by:
    0: From `load` at prelude/prelude.bzl:8:6-29
    1: From `load` at prelude/native.bzl:16:6-45
    2: From `load` at prelude/apple/apple_macro_layer.bzl:10:5-36
    3: From `load` at prelude/apple/apple_rules_impl_utility.bzl:8:6-46
    4: From `load` at prelude/apple/apple_bundle_types.bzl:8:6-18
    5: Error evaluating module: `prelude//apple/debug.bzl`
    6: error: Variable `AnalysisContext` not found
         --> prelude/apple/debug.bzl:42:36
          |
       42 | def get_aggregated_debug_info(ctx: AnalysisContext, debug_infos: list[AppleDebuggableInfo.type]) -> AggregatedAppleDebugInfo.type:
          |                                    ^^^^^^^^^^^^^^^
          |
```

**Comment by zjturner** [comment]
You need to install latest buck2 (or rebuild from source at trunk) to fix this issue.

**Comment by thoughtpolice** [comment]
To help smooth this out, for the moment I suggest you pick a binary pre-release, for example, [2023-08-01](https://github.com/facebook/buck2/releases/tag/2023-08-01) &mdash; aside from binaries, that tag includes an artifact called `prelude-hash` that tells you the proper git commit for the [buck2-prelude](https://github.com/facebook/buck2-prelude) repo.

As of tag `2023-08-01`, that commit is [acf49faaa61fd6ad9facd9e1418eed514bbb2ec8](https://github.com/facebook/buck2-prelude/tree/acf49faaa61fd6ad9facd9e1418eed514bbb2ec8), so downloading that copy of the prelude should work OK.

Really, this should be part of the release engineering process, since (I suspect) `buck2 init` gave you a wrong version of the prelude to tag as a submodule.

**Comment by miaoyipu** [comment]
This issue has been resolved by updating buck2 binary

**Comment by cormacrelf** [comment]
If you have cargo/rust installed, you can run `cargo install buckle` to automate much of the above.  You use `buckle` instead of invoking buck2 directly, and it pulls a buck2 binary based on a `.buckversion` file. It prints a warning when your prelude is out of sync.

**Comment by ndmitchell** [comment]
@cormacrelf - we should definitely add that on the website. I wonder if we should encourage that more heavily though? CC @themarwhal

**Comment by cormacrelf** [comment]
I am leaning towards using `direnv` for any bootstrapping needs, rather than buckle. This is thanks to `buck2-nix`, which showed the way. Nix can't be used on windows beyond WSL, but direnv is portable and really a very good way to address the problem of bootstrapping. I think a short python script could do what buckle does quite easily, and it could handle more cases. Buckle only supports mainline prelude and binary releases, but at the moment it's a bit out of reach to do everything you need to do without patching prelude at all. Once you patch your prelude, buckle is no longer very useful.

<details>
<summary>I have also been using the entire buck2 repo in a git subtree, rather than the prelude.</summary>

```sh
# add this repo as a subtree
git subtree add --prefix buck2 https://github.com/facebook/buck2.git main --squash
cd buck2 && cargo install --path app/buck2

# edit your .buckconfig
[repositories]
prelude = buck2/prelude

# later on, pull in latest changes and rebuild
git subtree pull --prefix buck2 https://github.com/facebook/buck2.git main --squash
cd buck2 && cargo install --path app/buck2
```

- The `--squash` is important if you don't want 8000 commits in your repo
- Any contributions back to buck2 prelude should be going to this repository anyway, so you can simply `git remote add buck2-fork https://...` and `git subtree push --prefix buck2 buck2-fork mybranch` to it.

This is not something I have done for use with a team yet, and for more than one developer you would also have to re-implement what buckle does. I think I will do that with direnv.

</details>

If you do that, and perhaps have some way of `buck2` reporting a custom version commit hash, then comparing it to `git log -- buck2 ':!buck2/prelude' will tell you if the direnv script needs to rebuild buck2. Could work, who knows.
