### ISSUE TITLE
Multithreaded actions under remote execution?

### ISSUE THREAD

**Issue by thetimmorland** [facebook/buck2#431]
I was reading through the prelude's haskell rules and noticed that the `_compile` function (https://github.com/facebook/buck2-prelude/blob/89fd005b56ead12430e9580dfdad3a96772df5e7/haskell/haskell.bzl#L588) only registers a single action which calls the haskell compiler on all `attrs.srcs`.

Assuming that the haskell compiler is `ghc` this action will implicitly use however many processors are available (https://downloads.haskell.org/ghc/latest/docs/users_guide/using.html?highlight=jobs#using-ghc-make). Would this lead to any problems when using remote-execution? For example, would the action be limited to a single thread?

**Comment by thoughtpolice** [comment]
Note that by default, GHC shouldn't use multiple cores without `-j`, when in make mode. So, by default that action is not multicore (unless I'm misreading the code.) It will always use one thread.

But let's assume it was, for the actual question. I think the basic answer is the same as Bazel, which is something like this, extremely simplified:

- The way individual actions are run is "up to you". So, you need to provision the build infrastructure "somehow."
- When using EngFlow/BuildBarn/BuildBuddy, on Linux, this boils down to "give them a container, run a command inside it"
- The number of vCPUs that container is given is basically arbitrary, but presumably could be 1-or-many.
- So, try not to oversubscribe or bottleneck those individual actions.

So, if you had a container run with 1 vCPU, and you ran `ghc --make -j`, it would (should!) only run with 1 core, since that's all the container was given &mdash; `-j` with no arguments detects the number of CPUs. What if you ran with, say, `-j4` and only had 1vCPU? Well, it would be oversubscribed, probably, and performance would be really bad. So, we want to avoid that.

There is a nit here, which is that I am *not* sure what GHC's "number of processors" logic is for `-j` mode, because `-j` sort of implicitly depends on `+RTS -N` also being active if you want that to work. Actually, I may have even written/implemented that very `+RTS -N` logic many years ago? I can't remember if I did? Maybe the initial version, or I code reviewed it. But I am about 99% sure it never did anything special to account for cgroup logic (i.e. a container's cgroup is given 1 core but the system has 8 cores, you want to detect 1 core, not 8.) The memory allocator, at least as far as I remember, isn't cgroup-aware... I consider those bugs that should be fixed, frankly. So please assume everything is in a universe where this is all correct for the purposes of this explanation.

---

Of course, it's important to remember that in the philosophy of Bazel and Buck2, remote execution is the key to scaling. This means the actions in your build need to be decomposed into small individual tasks, to the greatest extent possible, to take advantage of "scale out" builds.

So, in some ideal world, the Haskell rules would probably look closer to the way GHC's own build system works, which is that it interrogates the module dependency graph and runs `ghc -c` on every file individually. This has its own problems, namely that every invocation of `ghc` needs to reload the package database (along with all the types in interface files for typechecking, etc) whereas `ghc --make` only needs to do so once; this gives a memory/speed vs parallelism tradeoff. I suspect it might be the better option for Buck2 in the long run, but `--make` is certainly easier to use.

**Comment by thetimmorland** [comment]
Thanks so much for your detailed answer!
