### ISSUE TITLE
export_exe isn't available by default

### ISSUE THREAD

**Issue by thoughtpolice** [facebook/buck2#438]
Something I ran into last night: `prelude//export_exe.bzl` is pretty useful, but it's not exported by default, so you have to `load()` it before you can use it in a `BUCK` file. Is this intentional, or would a patch to change it be useful? (I guess it would also get attached to `native.` then, to be used in `.bzl` files?)

**Comment by cjhopman** [comment]
Hm, I think we'd like to move to a world where nothing is exported by default and everything needs to be explicitly loaded. idk if that principle is why this isn't exported and we're a long way off from that.

Note that one thing you can do is use the `buildfile.includes` config to basically extend the prelude. idk if I like that though because it can be really non-obvious to someone reading a buildfile that that's where the symbols are coming from (idk if the lsp jumps to def for them correctly or not, if it does that could mitigate this a little bit).

**Comment by thoughtpolice** [comment]
Yeah, in my own prelude I go the "explicit import route" for almost everything except some few trivial helpers; the global namespace only has about 5-7 things in it. But I figured since it was likely impractical for right now to make that change, that `export_exe` could go in. :)

The `buildfile.includes` thing is interesting; but I agree it probably makes readability worse. At least right now I can just point people to the single `load_symbols` call I make... So for now I think I'll close this; a single `load` statement with the normal prelude isn't the end of the world.
