### ISSUE TITLE
Issue in instantiation of bxl actions

### ISSUE THREAD

**Issue by satyajeet104** [facebook/buck2#451]
It seems bxl_actions() api is broken, when I try to run one script provided [here](https://github.com/facebook/buck2/blob/67bdedf3099dabcd9b3eecb6350eee4a9a60489c/prelude/debugging/fdb.bxl) I run into this error: 
```
buck2 bxl prelude//debugging/fdb.bxl:inspect_target -- --target=//app/buck2:buck2-bin
Traceback (most recent call last):
  File <builtin>, in <module>
  * prelude/debugging/fdb.bxl:94, in inspect_target_impl
      actions = ctx.bxl_actions().actions
error: Execution platforms are not enabled
  --> prelude/debugging/fdb.bxl:94:15
   |
94 |     actions = ctx.bxl_actions().actions
   |               ^^^^^^^^^^^^^^^^^
   |


Execution platforms are not enabled

Caused by:
    NoneError
```

I'm not sure if I'm doing anything wrong here. I even tried to run the examples given in the [documentation](https://buck2.build/docs/developers/bxl_how_tos/#running-actions) but I get the same error.

Buck Details:

**Buck2 Version**: 
```
buck2 --version
buck2 fee4e223d46cb9104bc2d39c869427ce7e7347a9 <build-id>
```

Last commit in my clone: [5cb0e8d8d9c48f8e7bdd0e509cfab887842f272e](https://github.com/facebook/buck2/commit/5cb0e8d8d9c48f8e7bdd0e509cfab887842f272e)

**Comment by wendy728** [comment]
You need to set up execution platforms for your project. In the .buckconfig's `build` section, you would need to add `execution_platforms`:

```
[build]
  execution_platforms = your_cell//path/to/platform/execution:platforms
```

You can take a look at the buildbarn example [here](https://github.com/facebook/buck2/blob/main/examples/remote_execution/buildbarn/.buckconfig#L12-L13) and see how its execution platform is set up. [Here](https://buck2.build/docs/rule_authors/configurations/#execution-platforms) is some more documentation about execution platforms as well.

I'll add some information in the BXL docs about this error, since it appears to not be documented anymore.

**Comment by satyajeet104** [comment]
Thanks Wendy, that fixed the issue
