### ISSUE TITLE
Define `cxx_library` for `git_fetch`ed sources

### ISSUE THREAD

**Issue by cbarrete** [facebook/buck2#467]
Is using `git_fetch` to define a `cxx_library` supported? I've had trouble with adding a party dependency without simply vendoring it (which I understand is the preferred method, but is also often unpopular for open source projects). If not, I'll just vendor the third party sources that I need in my repo, but it seems to me that this would be unsatisfying for open source adoption at large.

I've seen some helpful comments on https://github.com/facebook/buck2/discussions/387, which show how `http_archive` has convenient options for defining sub-targets, which `git_fetch` misses.
Besides that, I haven't found how to easily/conveniently:
1. avoid having to use weird include paths
2. get the headers within the library to successfully include each other without patching the source

See a rather contrived example (which doesn't attempt to get a full build going, just getting the headers right for now) at https://github.com/cbarrete/buck2_git_fetch.

Any pointers would be greatly appreciated!

**Comment by thoughtpolice** [comment]
Two things:

1) `git_fetch` should probably also take a `sub_targets` argument like `http_archive` does, for use cases like this.
2) In this case, because you're cloning a repo from github (that does not use submodules!), you can just use `http_archive` instead as an immediate workaround for `git_fetch` not supporting sub targets i.e. just download https://github.com/axboe/liburing/archive/298c083d75ecde5a8833366167b3b6abff0c8d39.tar.gz instead of using `git_fetch` at all.

As for the headers thing, the ultimate answer is you need to read the source code, and then use a combination of a few features from `cxx_library`:

- Use `exported_headers` for header files that dependent targets should be able to `#include`
- Use `headers` for header files that only the built target needs, i.e. this is where private headers goes
- `header_namespace` controls the "directory" all headers are under when setting up the compiler, i.e. `header_namespace = "foo"` means all headers from `exported_headers` and `headers` appear as `foo/...` in the source code.

`exported_headers` and `headers` also can not only take a list, but a mapping, so you can map raw source files to the right include path, i.e. something like the following:

```python
cxx_library(
    header_namespace = "foobar",
    headers = {
      "private/test.h": ":srcdir[include/test.h]",
    },
    exported_headers = {
      "api.h": ":srcdir[include/usr/api.h]",
    },
)
```

would mean:

- Dependent, downstream targets can include `foo/api.h` in order to import the public API
- When compiling the cxx_library itself, the `api.h` header can be imported as `foo/api.h` just like external cases
- It can also include `foo/private/test.h` as well, which is not exported to downstream consumers, and only available internally

Some details might be slightly off here but I think the combination of these behaviors should mostly allow you to craft the include paths to your liking.

**Comment by cbarrete** [comment]
Thanks for the detailed response. This all makes sense, I was having issues with the headers because I couldn't refer to them as sub-targets with `git_fetch`, but getting them via HTTP fixes that, so I guess I'll go that way for now.
It's a shame that I have to manually list out all files in the mappings (or write some starlark/bxl to automate that), but that will work for me for now, as I don't have too many dependencies at the moment.
