### ISSUE TITLE
Buck2 doesn't work with relative symlinks (or: how to use buck2 with symlinks?)

### ISSUE THREAD

**Issue by jazzdan** [facebook/buck2#474]
I talked with the buck2 team at the Build Meetup in Reykjavik about how to connect two separate git repositories via buck2. To make things concrete, in our case we have our closed source monorepo and our open source fork of chromium, which is a very large git repository and thus we don't want to bring it in to the monorepo if we can avoid it. Plus it's open source, whereas our monorepo is closed source. I think (and I might be misremembering) that they recommended that I create a symlink from our monorepo to chromium. They said that while buck2 won't track changes past that symlink boundary, it should otherwise work. When you want buck2 to rebuild chromium, change the name of the symlink.

This does work, but only if the symlink is absolute or if the target doesn't have any sources.

## Reproduction steps
I created a sample git repo to demonstrate the symlink behavior.

To reproduce:
1. `git clone https://github.com/jazzdan/buck2_relative_symlink_bug.git`
2. `cd buck2_relative_symlink_bug`
3. `cd project_a`
4. `buck2 build //project_b_relative/:hello_world`. You get this error:

```
Build ID: e4700e5f-3f99-4a32-9075-ee2db2e745c6
Jobs completed: 6. Time elapsed: 0.0s.
BUILD FAILED
Error accessing metadata for path `root//project_b_relative/source.txt`

Caused by:
    0: Invalid symlink at `project_b_relative`: `../project_b`
    1: expected a normalized path but got an un-normalized path instead: `../project_b`
```
5. `./make_absolute_symlink.sh` which makes an absolute symlink to ../project_b called `project_b_absolute`
6. `buck2 build //project_b_absolute:hello_world` works
7. `buck2 build //project_b_relative:hello_world_no_source` works just fine, even though `project_b_relative` is a relative symlink the fact that the target in question doesn't have any sources causes it to not trigger the error.

## Additional background
We build some binaries (tools, really) in the monorepo that I would like to hook up in the chromium build. We also would like to eventually consume chromium binaries in our integration tests. What I ultimately want to do is something like this:

<img width="1109" alt="CleanShot 2023-11-01 at 11 40 11@2x" src="https://github.com/facebook/buck2/assets/452453/34ded045-df3d-4861-aac7-cc8b726170f7">

Curious if there's a better way to approach this than the symlinking approach, or if we need to bit the bullet and use git submodules/a "real" monorepo". Thanks!

**Comment by ndmitchell** [comment]
Nice to meet you at the Build Meetup. I think the issue may be that I was a bit out of date with my Buck2 knowledge - we now have some level of support for symlinks inside the repo, which is breaking your approach. All paths inside the repo are stored relative to the root, so basically you are getting an error when trying to normalise the target of the symlink relative to the root. We have special support for absolute symlinks, since they never intended to be within the repo, and just treat them as links we don't care about.

If you don't reference the source file we don't try and create information about it, which is why everything is fine if you don't point at it.

I would suggest going the monorepo route. That's the best tested approach.

**Comment by jazzdan** [comment]
Thanks @ndmitchell. Adding a little pre-build step to make the symlink absolute is working for us now, though we would love to go with a real monorepo eventually.
