### ISSUE TITLE
macros are not supported in buck2

### ISSUE THREAD

**Issue by hutm** [facebook/buck2#490]
Macros (https://buck.build/extending/macros.html) that used to work in buck1 are no longer working in buck2. Buck2 documentation says they are `mostly compatible with buck1` https://buck2.build/docs/rule_authors/writing_rules/ 
What is missing to make it work in buck2?

minimal example to repro:
lib.bzl
```
load("@prelude//decls:python_rules.bzl", "python_library", "python_binary")

def a_python_library(**kwargs):
  kwargs["zip_safe"] = read_config('python', 'zip_safe') == 'True'
  python_library(
    **kwargs
  )
```
BUCK
``` 
load("//lib.bzl", "a_python_library")

a_python_library(
    name = 'hello',
    srcs = [ 'hello.py' ],
)
```

building
```
buck2 build ...
Build ID: c2fa4bab-922b-484b-a0b7-e75b0ba46611
Jobs completed: 4. Time elapsed: 0.0s.
BUILD FAILED
Error evaluating build file: `root//:BUCK`

Caused by:
    Traceback (most recent call last):
      * BUCK:10, in <module>
          a_python_library(
      * lib.bzl:5, in a_python_library
          python_library(
    error: Operation `call()` not supported on type `record`
     --> lib.bzl:5:3
      |
    5 |     python_library(
      |  ___^
    6 | |     **kwargs
    7 | |   )
      | |___^
      |

```

**Comment by ndmitchell** [comment]
The issue is that `load("@prelude//decls:python_rules.bzl", "python_library", "python_binary")` doesn't contain the Python rules, but in fact contains a pair of fields containing the pieces of the Python rule. To get the actual Python rules you can just do `python_library` (they are available by default) or load from `@prelude//decls:python_rules.bzl`. The `decls:python_rules.bzl` file is just an internal detail for the prelude.

The macro you describe should work very much the same between Buck1 and Buck2.

**Comment by zjturner** [comment]
> To get the actual Python rules you can just do python_library (they are available by default)

I’ve actually been wondering about this.  How are the rules available without loading?  Is it possible for someone outside of the prelude to create rules or macros that don’t need to be loaded?

**Comment by hutm** [comment]
python_library is indeed available without importing in buck1; in buck2 it throws an error:
```
BUILD FAILED
From load at BUCK:2

Caused by:
    0: Error evaluating module: `root//lib.bzl`
    1: error: Variable `python_library` not found, did you mean `a_python_library`?
        --> lib.bzl:5:3
         |
       5 |   python_library(
         |   ^^^^^^^^^^^^^^
         |
```

updated  `lib.bzl`
```
#load("@prelude//decls:python_rules.bzl", "python_library", "python_binary")

def a_python_library(**kwargs):
  kwargs["zip_safe"] = read_config('python', 'zip_safe') == 'True'
  python_library(
    **kwargs
  )
```

**Comment by hutm** [comment]
@ndmitchell , I am confi

> or load from `@prelude//decls:python_rules.bzl`.

@ndmitchell  I am not following the suggestion; I am loading from that file in `lib.bzl`. What has to updated to successfully load it?

**Comment by ndmitchell** [comment]
> How are the rules available without loading?

The prelude is preloaded in all `BUCK` files. When in a `.bzl` file it is loaded as `native`. That means, @hutm that `native.python_library` is probably what you want.

The use of `@prelude//decls:python_rules.bzl` will never work because it doesn't contain the Python rules - it contains records of fields that are later put together to form the Python rules.

@zjturner - you might be interested in the config key `buildfile.includes` which lets you preload a set of files within a cell. It's essentially as though that file is loaded in advance, which you can use to add things into your namespace without modifying the prelude.

**Comment by thoughtpolice** [comment]
> I’ve actually been wondering about this. How are the rules available without loading?

In the case of Prelude itself, the logic is pretty simple from what I've gathered, writing my own:

- Point the `prelude//` cell in `.buckconfig` to point anywhere.
- Buck implicitly loads the file `prelude//prelude.bzl` by default.
- Any public symbols exported from that file are by default available in all `BUCK` files, for immediate use. This includes functions, types, globals, etc.
- **Unless** those Buck files exist in the `prelude//` cell itself!
  - In that case you must `load()` the symbol you want explicitly.
  - This means `BUCK` files in the Prelude pretty much always have to explicitly `load()` something
  - This prevents (some) obvious recursive dependencies from creeping in.

As a side note, I think the fact that most language rules are available by default with no `load()` call is basically considered a design mistake and bad form today, from some comments I remember reading in the source code. But like many things, it's necessary for Buck1 compatibility. For my own Prelude, I effectively never ever export anything by default, except the absolute most important and generalized core Starlark code, types, and `rule()`s (like `alias`, `export_file`, `constraint_setting`, and `download_file`). Everything else, including language-specific code, absolutely must be imported by default with a `load()`.
