### ISSUE TITLE
Allow load to take variable string or functions that returns string

### ISSUE THREAD

**Issue by izissise** [facebook/buck2#709]
Hello,

In buck2 `load` statements can only take constant string as parameters, it would be nice if it could take anything that resolve to a string. This would allow to reduce refactoring pain when moving a directory:

```
# buck2/utils.bzl
def local_repo(file):
  return f'buck2/plugins/{file}'

# BUCK
load(local_repo('xxx'))
```

Thanks,
Hugues

**Comment by izissise** [comment]
Maybe it can be gated being a config flag, so it would still be forbidden for orgs that don't want this.

A similar issue exist for declaring function in BUCK files.

**Comment by izissise** [comment]
Would you accept a PR on this? @Nero5023

**Comment by Nero5023** [comment]
Such change would be significantly complicate. 

The starlark lifetime: `load` will happen first, then we evaluation the function body. That's means no code will happen before the `load` statements.

The change you mentioned above will totally change the logic, which is not easy.  I would not recommend to make such changes.

But I'm curious what exact the problem you want to solve here? If only about make it easy when moving a directory, I would recommend just using replace here.

**Comment by izissise** [comment]
I want to combine it with this issue https://github.com/facebook/buck2/issues/710
To have much more dynamism and liberty in the build system.
I think that's why `make` is still popular today, a program can generate a Makefile that `make` will re-ingest

**Comment by stepancheg** [comment]
This change is much larger than it seems.

For example, because of how starlark works: `load()` is a statement, not a function. And name resolution is static in starlark: `load(..., "y")` creates a symbol `y`, and before evaluation even starts, `y` is resolved to a loaded symbol.

#710 makes it even harder because of various constraints in buck2 (for example, synchronous evaluation of `BUCK` files).

We don't need this feature internally at the moment, because making build system too dynamic may reduce repository code quality for example, or performance. Automated code modding tools, static typecheckers, various linters are harder to do when the system is too dynamic.

We may want to have something like this exclusively for open-source version, however:
- Such changes cannot be made as a pull request. Design document is needed first.
- Someone inside the buck2 team need to drive the design process.
